kind: app
name: package
spec:
  routes:
    hours:
      get: /api/packages/:id
  settings:
    - hours
  filters:
    - cors
    - auth
  modules:
    - package
    - package_time
    - common_store
    - employer_only
    - session
    - http

