kind: app
name: project
spec:
  routes:
    hours:
      get: /api/projects/:id
  settings:
    - hours
  filters:
    - cors
    - auth
  modules:
    - project
    - common_store
    - session
    - http

