---
apiVersion: v1
kind: Service
metadata:
  name: bot
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  type: ClusterIP  
  ports:
  - name: bot
    port: 5000
  selector:
    app: bot
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: bot
spec:
  replicas: 1 
  serviceName: bot
  selector:
    matchLabels:
      app: bot
  template:
    metadata:
      labels:
        app: bot
    spec:
      imagePullSecrets:
        - name: docker
      containers:
        - name: bot
          imagePullPolicy: Always
          image: docker.pkg.github.com/pedro-gutierrez/elementary/elementary:latest
          ports:
            - name: bot
              containerPort: 5000
              protocol: TCP
          envFrom:
            - secretRef:
                name: secrets
          env:
            - name: DEPLOYMENT_VERSION 
              value: "{{VERSION}}"
---
apiVersion: v1
kind: Service
metadata:
  name: influxdb 
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  type: ClusterIP  
  ports:
  - name: influxdb
    port: 8086
  selector:
    app: influxdb
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: influxdb 
spec:
  replicas: 1  
  serviceName: influxdb
  selector:
    matchLabels:
      app: influxdb
  template:
    metadata:
      labels:
        app: influxdb
    spec:
      containers:
        - name: influxdb
          imagePullPolicy: IfNotPresent 
          image: influxdb 
          ports:
            - name: influxdb
              containerPort: 8086
              protocol: TCP
          envFrom:
            - secretRef:
                name: secrets
