apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nginx 
spec:
  replicas: 1 
  serviceName: eventbee
  selector:
    matchLabels:
      app: eventbee
  template:
    metadata:
      labels:
        app: eventbee
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
                - key: "app"
                  operator: In
                  values:
                  - eventbee
            topologyKey: "kubernetes.io/hostname"
      containers:
        - name: nginx
          image: nginx:1.14.2
          ports:
            - name: eventbee
              containerPort: 80
              protocol: TCP
          envFrom:
            - secretRef:
                name: secrets
          env:
            - name: DEPLOYMENT_VERSION
              value: "{{VERSION}}"
