---
apiVersion: v1
kind: Service
metadata:
  name: bot
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  type: ClusterIP  
  ports:
  - name: bot
    port: 5000
  selector:
    app: bot
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: bot
spec:
  replicas: 1 
  serviceName: bot
  selector:
    matchLabels:
      app: bot
  template:
    metadata:
      labels:
        app: bot
    spec:
      imagePullSecrets:
        - name: docker
      containers:
        - name: bot
          imagePullPolicy: Always
          image: docker.pkg.github.com/pedro-gutierrez/elementary/elementary:latest
          ports:
            - name: bot
              containerPort: 5000
              protocol: TCP
          envFrom:
            - secretRef:
                name: secrets
          env:
            - name: DEPLOYMENT_VERSION 
              value: "{{VERSION}}"
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  type: ClusterIP  
  ports:
  - name: prometheus 
    port: 9090
  selector:
    app: prometheus
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval:     5s 
      evaluation_interval: 5s 
    scrape_configs:
      - job_name: 'bot'
        static_configs:
          - targets:
              - bot:5000
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: prometheus
spec:
  replicas: 1  
  serviceName: prometheus 
  selector:
    matchLabels:
      app: prometheus 
  template:
    metadata:
      labels:
        app: prometheus 
    spec:
      volumes:
      - name: prometheus-config
        configMap:
          name: prometheus-config
      containers:
        - name: prometheus
          image: prom/prometheus:v2.26.0
          imagePullPolicy: IfNotPresent 
          args:
            - --storage.tsdb.retention=24h
            - --config.file=/etc/prometheus/prometheus.yml
          command:
            - /bin/prometheus
          ports:
            - name: web 
              containerPort: 9090
              protocol: TCP
          volumeMounts:
            - name: prometheus-config
              mountPath: /etc/prometheus

