---
apiVersion: v1
kind: Service
metadata:
  name: eventbee
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  type: ClusterIP  
  ports:
  - name: eventbee
    port: 4000
  selector:
    app: eventbee
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: eventbee
spec:
  replicas: 2 
  serviceName: eventbee
  selector:
    matchLabels:
      app: eventbee
  template:
    metadata:
      labels:
        app: eventbee
    spec:
      containers:
        - name: eventbee
          imagePullPolicy: Always
          image: pedrogutierrez/eventbee:latest
          ports:
            - name: eventbee
              containerPort: 4000
              protocol: TCP