---
apiVersion: v1
kind: Service
metadata:
  name: eventbee
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  type: ClusterIP  
  ports:
  - name: eventbee
    port: 4000
  selector:
    app: eventbee
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: eventbee
spec:
  replicas: 3 
  serviceName: eventbee
  selector:
    matchLabels:
      app: eventbee
  template:
    metadata:
      labels:
        app: eventbee
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
                - key: "app"
                  operator: In
                  values:
                  - eventbee
            topologyKey: "kubernetes.io/hostname"
      containers:
        - name: eventbee
          imagePullPolicy: Always
          image: pedrogutierrez/eventbee:latest
          ports:
            - name: eventbee
              containerPort: 4000
              protocol: TCP
          env:
            - name: ELEMENTARY_VERSION
              value: "elementary_version"