kind: module
name: project
spec:
  decoders:
    http:
      get:
        method: GET
        params:
          id:
            any: text
    store:
      project:
        project:
          any: object
      time:
        time:
          any: list
  update:
    get:
      model:
        id: @data.params.id
      cmds:
        store: fetch
    project:
      model:
        project: @data.project
      cmds:
        store: find_time
    time:
      model:
        data:
          merge:
            - @model.project
            - hours:
                reduce: @data.time
                initial: 0
                with:
                  sum:
                    - @acc
                    - @item.time
      cmds:
        return: data
  encoders:
    fetch:
      store: @store
      fetch:
        id: @id
      from: projects
      as: project
    find_time:
      store: @store
      find:
        project: @project.id
      from: time
      as: time
