apiVersion: v1
kind: Service
metadata:
  name: eventbee
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  type: ClusterIP  
  ports:
  - name: eventbee
    port: 4000
  selector:
    app: eventbee