version: 2.1
jobs:
  build:
    docker:
      - image: circleci/elixir:1.10.1
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Install Heroku CLI (If not installed)
          command: |
            if [[ $(command -v heroku) == "" ]]; then
              curl https://cli-assets.heroku.com/install.sh | sh
            else
              echo "Heroku is already installed. No operation was performed."
            fi
      - run:
          name: Build images
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker build -t pedrogutierrez/elementary:latest .
            docker build -t pedrogutierrez/hours:latest -f Dockerfile.hours .

      - run:
          name: Publish images
          command: |
            docker push pedrogutierrez/elementary:latest
            docker push pedrogutierrez/hours:latest
      - run:
          name: Deploy to Heroku
          command: |
            docker login --username=$HEROKU_LOGIN --password=$HEROKU_API_KEY registry.heroku.com
            docker tag pedrogutierrez/hours:latest registry.heroku.com/floohours/web
            docker push registry.heroku.com/floohours/web
            heroku container:release -a floohours web
