version: 2.1
orbs:
  heroku: betterdoc/deploy-to-heroku@4.1.0
jobs:
  build:
    docker:
      - image: circleci/elixir:1.10.1
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build images
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker build -t pedrogutierrez/elementary:latest .
            docker build -t pedrogutierrez/hours:latest -f Dockerfile.hours .
            docker push pedrogutierrez/elementary:latest
            docker push pedrogutierrez/hours:latest
            docker tag pedrogutierrez/hours:latest registry.heroku.com/floohours/web
      - heroku/docker-build-release:
          app-name: floohours
          app-type: web
