kind: port
name: default
spec:
  port:
    env: PORT
    default: 8080
  apps:
    health:
      http: /api/health
    store:
      http: /api/stores/:name
    packages:
      http: /api/packages
    package:
      http: /api/packages/:id
    projects:
      http: /api/projects
    project:
      http: /api/projects/:id
    users:
      http: /api/users
    user:
      http: /api/users/:id
    assignments:
      http: /api/assignments
