kind: port
name: default
spec:
  port:
    env: PORT
  apps:
    health:
      http: /api/health
    store:
      http: /api/stores/:name
    register:
      http: /api/register
    passwd_forgot:
      http: /api/passwd/forgot
    passwd_reset:
      http: /api/passwd/reset
    login:
      http: /api/login
    packages:
      http: /api/packages
    package:
      http: /api/packages/:id
    projects:
      http: /api/projects
    project:
      http: /api/projects/:id
    users:
      http: /api/users
    user:
      http: /api/users/:id
    assignments:
      http: /api/assignments
