kind: port
name: default
spec:
  port: 8080
  apps:
    health:
      http: /api/health
    store:
      http: /api/stores/:name
    packages:
      http: /api/packages
    projects:
      http: /api/projects
    assignments:
      http: /api/assignments
    users:
      http: /api/users
