kind: module
name: products
spec:
  init:
    model:
      data:
        - id: PROD-7YC371846A4660914
          name: fullpass
          short: fp
          title:
            en: Full Pass
            fr: Full Pass
            es: Full Pass
          icon: fas fa-ticket-alt
          description:
            en: Your last minute pass to your next favourite social event
            fr: Votre pass de denière minute pour votre prochain évènement social favori
            es: Tu pase de última hora, para tu próximo evento social favorito
          features:
            - name: event-import
              icon: fas fa-cloud-upload-alt
              title:
                en: Import events 
                fr: Importer des évènements 
                es: Importar eventos
            - name: event-verify
              title:
                en: Verify events 
                fr: Vérifier des évènements 
                es: Verificar eventos
            - name: event-link
              title:
                en: Link events 
                fr: Relier des évènements 
                es: Relacionar eventos
            - name: next-events 
              title:
                en: Next events 
                fr: Prochains évènements 
                es: Eventos próximos
            - name: show-event
              title:
                en: Event detail 
                fr: Détail de l'évènements 
                es: Detalle del evento 
            - name: event-search
              title:
                en: Search events 
                fr: Recherche d'évènements 
                es: Buscar eventos
            - name: event-subscriptions
              title:
                en: Event subscriptions
                fr: Souscrire a des èvenements
                es: Subscripciones a eventos
            - name: pass-offer 
              title:
                en: Pass offer
                fr: Offre de Pass
                es: Oferta de pases
            - name: pass-verify 
              title:
                en: Verify pass 
                fr: Vérification de Pass
                es: Verificación de pases
            - name: pass-demand 
              title:
                en: Pass demand
                fr: Offre de Pass
                es: Oferta de pases
            - name: priority-match
              title:
                en: Priority Match
                fr: Matching en priorité 
                es: Matching con prioridad
            - name: notifications
              title:
                en: Notifications
                fr: Notifications 
                es: Notificaciones 
        ##- id: PROD-4J423377F7256584M
        ##  name: corpbee
        ##  public: false
        ##  title:
        ##    en: Corp Bee
        ##    fr: Corp Bee
        ##    es: Corp Bee
        ##  icon: 
        ##  description:
        ##    en: Keep an eye on your favourite corporation
        ##    fr: Suivi de vos sociétés favories
        ##    es: Sigue en detalle a tus empresas favoritas
       # - id: PROD-7YC371846A4660915
       #   name: cloud
       #   public: false
       #   title:
       #     en: Cloud
       #     fr: Cloud
       #     es: Nube
       #   icon: fas fa-cloud
       #   description:
       #     en: Relax, and let us run your APIs, rock solid, on the BEAM
       #     fr: Détentez vois, pendant que nous prenon soins de vos APIs, solidement, sur la BEAM
       #     es: Relájate, mientras que nosotros corremos sus APIs, sólidas como una roca, sobre la BEAM
        - id: PROD-7YC371846A4660916
          name: consulting
          public: true
          title: 
            en: Elixir Consultancy
            fr: Conseil Elixir 
            es: Consultoría Elixir
          icon: fas fa-hands-helping
          description:
            en: Getting started with Erlang or Elixir? Let's talk about it!
            fr: Vous démarrez avec Erlang ou Elixir? Nous pouvons vous aider!
            es: Empezando con Erlang o Elixir? Te podemos ayudar!