name: Deploy App
on:
  push:
    branches:
      - master
    paths:
      - lib/**.*
      - examples/**.*
      - mix.exs
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup a0
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_A0 }}
          username: root
          key: ${{ secrets.SSH_PRIV_KEY }}
          script_stop: true
          script: |
            cmtool app
      - name: Setup a1
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_A1 }}
          username: root
          key: ${{ secrets.SSH_PRIV_KEY }}
          script_stop: true
          script: |
            cmtool app
      - name: Setup a2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_A2 }}
          username: root
          key: ${{ secrets.SSH_PRIV_KEY }}
          script_stop: true
          script: |
            cmtool app
