name: Deploy
on:
  push: {}
  schedule: 
    - cron:  '0 2 * * *'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Publish Docker
      uses: pedro-gutierrez/docker-action@v10
      with:
        password: ${{ secrets.DOCKER_PASSWORD }}
        tag: latest
    # - name: Deploy
    #   uses: pedro-gutierrez/apply-action@v7
    #   with:
    #     kubeconfig: ${{ secrets.KUBE_CONFIG }}
    #     password: ${{ secrets.DOCKER_PASSWORD }}