name: Deploy
on:
  push: {}
  schedule: 
    - cron:  '0 2 * * *'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: erlef/setup-beam@v1.7.2
      with:
        elixir-version: '1.12.2'
        otp-version: '24.0.3'
    - name: Checkout
      uses: actions/checkout@master
    - name: Deploy
      uses: pedro-gutierrez/deploy-action@v17
      with:
        docker_tag: latest
        docker_password: ${{ secrets.DOCKER_PASSWORD }}
        kubeconfig: ${{ secrets.KUBE_CONFIG }}
        secrets_name: "secrets"
        secrets: ${{ secrets.SECRETS }}
