name: Deploy to Okteto
on:
  - push
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@master
    - name: Login to Okteto
      uses: okteto/login@master
      with:
        token: ${{ secrets.OKTETO_TOKEN }}
    - name: "Activate personal namespace"
      uses: okteto/namespace@master
      with:
        name: pedro-gutierrez
    - name: "Create deployment"
      uses: okteto/apply@master
    - name: Sleep for 30 seconds
      uses: jakejarvis/wait-action@v0.1.0
      with:
        time: '30s'
    - name: Verify
      uses: srt32/uptime@v0.2
      with:
        url-to-hit: "https://eventbee-pedro-gutierrez.cloud.okteto.net/api/health"
        expected-statuses: "200"