name: Deploy to Okteto
on:
  push: {}
  schedule: 
    - cron:  '0 2 * * *'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Get code 
      uses: actions/checkout@master
   # - name: Build
   #   uses: docker/build-push-action@v1
   #   with:
   #     username: ${{ secrets.DOCKER_USERNAME }}
   #     password: ${{ secrets.DOCKER_PASSWORD }}
   #     repository: pedrogutierrez/eventbee
   #     tags: latest
    - uses: pedro-gutierrez/elementary-action@v3
      name: Deploy
      with:
        kubeconfig: ${{ secrets.KUBE_CONFIG }}