name: Deploy to Okteto
on:
  push: {}
  schedule: 
    - cron:  '* */2 * * *'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Get current date
      id: time
      run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
    - name: Checkout code
      uses: actions/checkout@master
   # - name: Build and push Docker image
   #   uses: docker/build-push-action@v1
   #   with:
   #     username: ${{ secrets.DOCKER_USERNAME }}
   #     password: ${{ secrets.DOCKER_PASSWORD }}
   #     repository: pedrogutierrez/eventbee
   #     tags: latest
    - name: Login to Okteto
      uses: okteto/login@master
      with:
        token: ${{ secrets.OKTETO_TOKEN }}
    - name: "Activate personal namespace"
      uses: okteto/namespace@master
      with:
        name: pedro-gutierrez
    - name: Set deployment version
      uses: jacobtomlinson/gha-find-replace@master
      with:
        find: deployment_version 
        replace: ${{ GITHUB_SHA }}
        include: k8s.yml
    - name: Set deployment date 
      uses: jacobtomlinson/gha-find-replace@master
      with:
        find: deployment_date 
        replace: ${{ steps.item.outputs.date }}
        include: k8s.yml
    - name: "Create deployment"
      uses: okteto/apply@master
    - name: Sleep for 30 seconds
      uses: jakejarvis/wait-action@v0.1.0
      with:
        time: '30s'
    - name: Verify
      uses: srt32/uptime@v0.2
      with:
        url-to-hit: "https://eventbee-pedro-gutierrez.cloud.okteto.net/api/health"
        expected-statuses: "200"