name: Deploy to Okteto
on:
  push: {}
  schedule: 
    - cron:  '0 2 * * *'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Git tags
      uses: rlespinasse/github-slug-action@v2.x
    - name: Current date
      id: time
      run: echo "::set-output name=date::$(date +%F-%T)"
    - name: Checkout code
      uses: actions/checkout@master
    - name: Build and push Docker image
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: pedrogutierrez/eventbee
        tags: latest
    - name: Login to Okteto
      uses: okteto/login@master
      with:
        token: ${{ secrets.OKTETO_TOKEN }}
    - name: "Activate personal namespace"
      uses: okteto/namespace@master
      with:
        name: pedro-gutierrez
    - name: Set Elementary version
      uses: jacobtomlinson/gha-find-replace@master
      with:
        find: elementary_version 
        replace: ${{ steps.time.outputs.date }}-${{ env.GITHUB_SHA_SHORT }}
        include: k8s.yml
    - name: "Create deployment"
      uses: okteto/apply@master
    - name: Wait for Application
      uses: nev7n/wait_for_response@v1
      with:
        url: "https://eventbee-pedro-gutierrez.cloud.okteto.net/api/health"
        responseCode: 200
        timeout: 120000 
        interval: 1000