name: Deploy to Okteto
on:
  - push
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@master
    - name: Login to Okteto
      uses: okteto/login@master
      with:
        token: ${{ secrets.OKTETO_TOKEN }}
    - name: "Activate personal namespace"
      uses: okteto/namespace@master
      with:
        name: pedro-gutierrez
    - name: "Create deployment"
      uses: okteto/apply@master